name: Dependency Review

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          retry-on-snapshot-warnings: true
          config-file: 'ctcampbellcom/blueoak-to-dependency-review/dist/blueoak-licenses.yml@main'